version: "3.8"
services:
  express-app:
    build:
      target: production
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 6s
#  watchtower:
#    image: containrrr/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 600


