version: "3.8"
services:
  express-app:
    build:
      target: production
    environment:
      - NODE_ENV=production
  watchtower:
    image: container/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


