version: "3.8"
services:
  express-app:
    image: ikhunaizi19/my-express-app
    build: .
    env_file:
      - .env
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - express-app




